import "@/styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import "antd/dist/reset.css";
import { ConfigProvider } from "antd";
export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Sloth Denver</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ConfigProvider
        theme={{
          token: {
            colorPrimary: "#F1FF00",
          },
        }}
      >
        <Component {...pageProps} />
      </ConfigProvider>
    </>
  );
}
